### ISSUE TITLE
Version mismatch kombu 3.0.37 abd amqp 1.4.7

### ISSUE THREAD

**Issue by l1ph0x** [edx/notifier#54]
This issue concerns Notifier on open-release/ginkgo.master. (Native install on Ubuntu Server 16.04)

The version mismatch between the two causes connection error as shown below in Err logs.

To solve this problem and make Notifier work install the required version of ampq
**(notifier) notifier@edx:~$ pip install amqp==1.4.9**

---
Err Log:
---
2018-07-07 15:18:16,483 [INFO] [service_name=notifier] [consumer] Connected to django://localhost//
2018-07-07 15:18:16,570 [WARNING] [service_name=notifier] [log] celery@edx ready.
2018-07-07 15:20:01,919 [INFO] [service_name=notifier] [strategy] Received task: notifier.tasks.do_forums_digests[6a0a8977-e751-4750-8060-629b8e0db7e4]
2018-07-07 15:20:02,169 [INFO] [service_name=notifier] [tasks] Beginning forums digest task: from_dt=2018-07-07 15:15:00 to_dt=2018-07-07 15:20:00
2018-07-07 15:20:02,174 [INFO] [service_name=notifier] [user] calling user api for digest subscribers
2018-07-07 15:20:03,410 [INFO] [service_name=notifier] [job] Task notifier.tasks.do_forums_digests[6a0a8977-e751-4750-8060-629b8e0db7e4] retry: Retry in 60s: UserServiceException('HTTP Error 403: FORBIDDEN',)
2018-07-07 15:20:06,987 [INFO] [service_name=notifier] [strategy] Received task: notifier.tasks.do_forums_digests[6a0a8977-e751-4750-8060-629b8e0db7e4] eta:[2018-07-07 15:21:03.345547+00:00]
2018-07-07 15:20:22,065 [INFO] [service_name=notifier] [strategy] Received task: notifier.tasks.generate_and_send_digests[b2880b47-2117-4811-bdf6-4ceba13633a2]
2018-07-07 15:20:22,097 [INFO] [service_name=notifier] [connection_wrapper] initialized connection wrapper with email backend: <django.core.mail.backends.smtp.EmailBackend object at 0x7f366d5666d0>
2018-07-07 15:20:22,107 [INFO] [service_name=notifier] [pull] calling comments service to pull digests for 1 user(s)
2018-07-07 15:20:22,733 [INFO] [service_name=notifier] [job] Task notifier.tasks.generate_and_send_digests[b2880b47-2117-4811-bdf6-4ceba13633a2] succeeded in 0.655033636998s: None
2018-07-07 15:21:03,565 [INFO] [service_name=notifier] [tasks] Retrying forums digest task: from_dt=2018-07-07 15:15:00 to_dt=2018-07-07 15:20:00
2018-07-07 15:21:03,571 [INFO] [service_name=notifier] [user] calling user api for digest subscribers
2018-07-07 15:21:03,764 [INFO] [service_name=notifier] [job] Task notifier.tasks.do_forums_digests[6a0a8977-e751-4750-8060-629b8e0db7e4] retry: Retry in 60s: UserServiceException('**HTTP Error 403: FORBIDDEN**',)
2018-07-07 15:21:07,267 [INFO] [service_name=notifier] [strategy] Received task: notifier.tasks.do_forums_digests[6a0a8977-e751-4750-8060-629b8e0db7e4] eta:[2018-07-07 15:22:03.705670+00:00]
root@edx:~#

**Comment by eazaika** [comment]
Done this, but error still exist:
```
2019-03-04 11:06:22,124 [INFO] [service_name=notifier] [job] Task notifier.tasks.do_forums_digests[d6233410-e84d-41b5-aa82-fcdcdedb837b] retry: Retry in 60s: UserServiceException('HTTP Error 403: Forbidden',)
2019-03-04 11:06:25,861 [INFO] [service_name=notifier] [strategy] Received task: notifier.tasks.do_forums_digests[d6233410-e84d-41b5-aa82-fcdcdedb837b] eta:[2019-03-04 11:07:22.040371+00:00]
2019-03-04 11:07:22,769 [INFO] [service_name=notifier] [tasks] Retrying forums digest task: from_dt=2019-03-04 11:00:00 to_dt=2019-03-04 11:05:00
2019-03-04 11:07:22,783 [INFO] [service_name=notifier] [user] calling user api for digest subscribers
2019-03-04 11:07:22,947 [ERROR] [service_name=notifier] [log] Task notifier.tasks.do_forums_digests[d6233410-e84d-41b5-aa82-fcdcdedb837b] raised unexpected: UserServiceException('HTTP Error 403: Forbidden',)
Traceback (most recent call last):
  File "/edx/app/notifier/virtualenvs/notifier/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/edx/app/notifier/virtualenvs/notifier/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/edx/app/notifier/src/notifier/tasks.py", line 159, in do_forums_digests
    raise do_forums_digests.retry(exc=e)
  File "/edx/app/notifier/virtualenvs/notifier/local/lib/python2.7/site-packages/celery/app/task.py", line 670, in retry
    maybe_reraise()
  File "/edx/app/notifier/virtualenvs/notifier/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 242, in maybe_reraise
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/edx/app/notifier/src/notifier/tasks.py", line 156, in do_forums_digests
    for user_batch in batch_digest_subscribers():
  File "/edx/app/notifier/src/notifier/tasks.py", line 125, in batch_digest_subscribers
    for v in get_digest_subscribers():
  File "/edx/app/notifier/src/notifier/user.py", line 61, in get_digest_subscribers
    data = _http_get(api_url, params=params, headers=_headers(), **_auth()).json()
  File "/edx/app/notifier/src/notifier/user.py", line 41, in _http_get
    response.reason
UserServiceException: HTTP Error 403: Forbidden
```
At the sudo -H -u notifier bash amqp==1.4.7. After update amqp==1.4.9 and rebooting got the same error(

**Comment by l1ph0x** [comment]
Are you running ginkgo.master?

**Comment by l1ph0x** [comment]
Since this is not a place for discussions, please create a new topic
in the Open
edX Ops group on Google
<https://groups.google.com/forum/#!forum/openedx-ops>
so that I am able to reply there.

**Comment by eazaika** [comment]
Oh, no, it's hawthorn.master

пн, 4 мар. 2019 г. в 22:30, l1ph0x <notifications@github.com>:

> Are you running ginkgo.master?
>

**Comment by l1ph0x** [comment]
@eazaika Since this is not a place for discussions, please create a new post at [https://groups.google.com/forum/#!forum/openedx-ops](url) so that I can reply there. Meantime, I am going to test Open edx Notifier for open-release/hawthron.master
